[package]
name = "rjson"
version = "0.1.0"
authors = ["YANGJIWEI1992 <yangjiwei@hinterstellar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
